-- menage.tagriculture definition

CREATE TABLE `tagriculture` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `agriculture-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `occ` int NOT NULL,
  `ag00` int DEFAULT NULL,
  `ag0l` text,
  `ag02a` int DEFAULT NULL,
  `ag02b` int DEFAULT NULL,
  `ag02c` int DEFAULT NULL,
  `ag02d` int DEFAULT NULL,
  `ag02e1` int DEFAULT NULL,
  `ag02e2` int DEFAULT NULL,
  KEY `idx_agriculture_level1id` (`level-1-id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- menage.tcaracteristique definition

CREATE TABLE `tcaracteristique` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `caracteristique-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `occ` int NOT NULL,
  `c00` int DEFAULT NULL,
  `c01n` text,
  `c01p` text,
  `c01` text,
  `c02` int DEFAULT NULL,
  `c03` int DEFAULT NULL,
  `c04` int DEFAULT NULL,
  `c05` text,
  `c05_jj` int DEFAULT NULL,
  `c05_mm` int DEFAULT NULL,
  `c05_aaaa` int DEFAULT NULL,
  `c06` int DEFAULT NULL,
  `c07` int DEFAULT NULL,
  `c07r` int DEFAULT NULL,
  `c07d` int DEFAULT NULL,
  `c07c` int DEFAULT NULL,
  `c08a` int DEFAULT NULL,
  `c08b` int DEFAULT NULL,
  `c08c` text,
  `c09` int DEFAULT NULL,
  `c10` int DEFAULT NULL,
  `c10a` text,
  `c11p10` int DEFAULT NULL,
  `c11r10` int DEFAULT NULL,
  `c11d10` int DEFAULT NULL,
  `c11c10` int DEFAULT NULL,
  `c11m10` int DEFAULT NULL,
  `c11m10a` text,
  `c11p5` int DEFAULT NULL,
  `c11r5` int DEFAULT NULL,
  `c11d5` int DEFAULT NULL,
  `c11c5` int DEFAULT NULL,
  `c11m5` int DEFAULT NULL,
  `c11m5a` text,
  `c11p1` int DEFAULT NULL,
  `c11r1` int DEFAULT NULL,
  `c11d1` int DEFAULT NULL,
  `c11c1` int DEFAULT NULL,
  `c11m1` int DEFAULT NULL,
  `c11m1a` text,
  `c11me` int DEFAULT NULL,
  `c11ae` int DEFAULT NULL,
  `c12` int DEFAULT NULL,
  `c13` int DEFAULT NULL,
  `c14` int DEFAULT NULL,
  `c15a` int DEFAULT NULL,
  `c15b` int DEFAULT NULL,
  `c15c` int DEFAULT NULL,
  `c15d` int DEFAULT NULL,
  `c15e` int DEFAULT NULL,
  `c15f` int DEFAULT NULL,
  `c15g` int DEFAULT NULL,
  `c15h` int DEFAULT NULL,
  `c16a` int DEFAULT NULL,
  `c16b` int DEFAULT NULL,
  `c16ba` text,
  `c16c` int DEFAULT NULL,
  `c16d` int DEFAULT NULL,
  `c16e` int DEFAULT NULL,
  `c16` int DEFAULT NULL,
  `c16f` int DEFAULT NULL,
  `c17` text,
  `c17a` text,
  `c18` int DEFAULT NULL,
  `c18a` int DEFAULT NULL,
  `c18b` int DEFAULT NULL,
  `c19` text,
  `c20` text,
  `c21` int DEFAULT NULL,
  `c21a` text,
  `c22` text,
  `c22a` int DEFAULT NULL,
  `c23` int DEFAULT NULL,
  `c23a` int DEFAULT NULL,
  `c24_t` int DEFAULT NULL,
  `c24_m` int DEFAULT NULL,
  `c24_f` int DEFAULT NULL,
  `c25_t` int DEFAULT NULL,
  `c25_m` int DEFAULT NULL,
  `c25_f` int DEFAULT NULL,
  `c26_t` int DEFAULT NULL,
  `c26_m` int DEFAULT NULL,
  `c26_f` int DEFAULT NULL,
  `c27_t` int DEFAULT NULL,
  `c27_m` int DEFAULT NULL,
  `c27_f` int DEFAULT NULL,
  `c28` text,
  `c29` int DEFAULT NULL,
  `membre_controle` int DEFAULT NULL,
  `is_deleted` int DEFAULT NULL,
  `tranche_age` varchar(7) DEFAULT NULL,
  `age_19_45` int NOT NULL DEFAULT '0',
  KEY `idx_caracteristique_stats` (`level-1-id`,`c03`,`c06`),
  KEY `idx_caracteristique_femmes_age` (`c03`,`c06`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- menage.tdeces definition

CREATE TABLE `tdeces` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `deces-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `occ` int NOT NULL,
  `d02` int DEFAULT NULL,
  `d03` int DEFAULT NULL,
  `d04` int DEFAULT NULL,
  `d05` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- menage.televage definition

CREATE TABLE `televage` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `elevage-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `occ` int NOT NULL,
  `e001` int DEFAULT NULL,
  `e002` text,
  `e003` int DEFAULT NULL,
  `e004` int DEFAULT NULL,
  `e005` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- menage.temigration definition

CREATE TABLE `temigration` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `emigration-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `occ` int NOT NULL,
  `em02` int DEFAULT NULL,
  `em03n` text,
  `em03p` text,
  `em04` int DEFAULT NULL,
  `em05` int DEFAULT NULL,
  `em06m` int DEFAULT NULL,
  `em06a` int DEFAULT NULL,
  `em07` int DEFAULT NULL,
  `em08` int DEFAULT NULL,
  `em09` int DEFAULT NULL,
  `em09a` text,
  `em10` int DEFAULT NULL,
  `em11` int DEFAULT NULL,
  `em12` int DEFAULT NULL,
  `em12a` text,
  KEY `idx_emigration_level1id` (`level-1-id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- menage.thabitat definition

CREATE TABLE `thabitat` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `habitat-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `h01` int DEFAULT NULL,
  `h01a` text,
  `h02` int DEFAULT NULL,
  `h03` int DEFAULT NULL,
  `h03a` text,
  `h04` int DEFAULT NULL,
  `h04a` text,
  `h05` int DEFAULT NULL,
  `h05a` text,
  `h06a` int DEFAULT NULL,
  `h06b` int DEFAULT NULL,
  `h07` int DEFAULT NULL,
  `h07a` text,
  `h07m` int DEFAULT NULL,
  `h08` int DEFAULT NULL,
  `h08a` text,
  `h09` int DEFAULT NULL,
  `h09a` text,
  `h10` int DEFAULT NULL,
  `h10a` text,
  `h11` int DEFAULT NULL,
  `h11a` text,
  `h12` int DEFAULT NULL,
  `h12a` text,
  `h13` int DEFAULT NULL,
  `h13a` text,
  `h141` int DEFAULT NULL,
  `h14110` int DEFAULT NULL,
  `h142` int DEFAULT NULL,
  `h143` int DEFAULT NULL,
  `h14on` int DEFAULT NULL,
  `h14re` int DEFAULT NULL,
  `h144` int DEFAULT NULL,
  `h145a` int DEFAULT NULL,
  `h145` int DEFAULT NULL,
  `h144a` int DEFAULT NULL,
  `h146` int DEFAULT NULL,
  `h147` int DEFAULT NULL,
  `h1481` int DEFAULT NULL,
  `h148` int DEFAULT NULL,
  `h149` int DEFAULT NULL,
  `h1410` int DEFAULT NULL,
  `h1411` int DEFAULT NULL,
  `h1412` int DEFAULT NULL,
  `h1413` int DEFAULT NULL,
  `h1414` int DEFAULT NULL,
  `h1415` int DEFAULT NULL,
  `h1416` int DEFAULT NULL,
  `h14161` int DEFAULT NULL,
  `h1417` int DEFAULT NULL,
  `h1418` int DEFAULT NULL,
  `h1419` int DEFAULT NULL,
  `h1420` int DEFAULT NULL,
  `h1421` int DEFAULT NULL,
  `h1422` int DEFAULT NULL,
  `h1423` int DEFAULT NULL,
  `h1424` int DEFAULT NULL,
  `h14m` int DEFAULT NULL,
  `h14r` int DEFAULT NULL,
  `h14w` int DEFAULT NULL,
  `h14de` int DEFAULT NULL,
  `h1425` int DEFAULT NULL,
  `h1426` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- menage.tmenage definition

CREATE TABLE `tmenage` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `menage-id` int NOT NULL,
  `level-1-id` int NOT NULL,
  `id01` int DEFAULT NULL,
  `id02` int DEFAULT NULL,
  `id03` int DEFAULT NULL,
  `id04` int DEFAULT NULL,
  `id05` int DEFAULT NULL,
  `id06` int DEFAULT NULL,
  `id07` int DEFAULT NULL,
  `xm01` int DEFAULT NULL,
  `xm02` int DEFAULT NULL,
  `xm02g` int DEFAULT NULL,
  `xm03` int DEFAULT NULL,
  `xm04` int DEFAULT NULL,
  `xm05` int DEFAULT NULL,
  `xm05i` int DEFAULT NULL,
  `xm06` int DEFAULT NULL,
  `xm07` int DEFAULT NULL,
  `xm07c` int DEFAULT NULL,
  `xm08l` text,
  `xm08` int DEFAULT NULL,
  `xm09` int DEFAULT NULL,
  `xm10` int DEFAULT NULL,
  `xm12` int DEFAULT NULL,
  `xm12lo` int DEFAULT NULL,
  `xm12la` int DEFAULT NULL,
  `xm12al` int DEFAULT NULL,
  `xm12pr` int DEFAULT NULL,
  `xm13` int DEFAULT NULL,
  `xm13a` int DEFAULT NULL,
  `xm14` int DEFAULT NULL,
  `xm14_jj` int DEFAULT NULL,
  `xm14_mm` int DEFAULT NULL,
  `xm14_aaaa` int DEFAULT NULL,
  `xm15` int DEFAULT NULL,
  `xm15h` int DEFAULT NULL,
  `xm15l` int DEFAULT NULL,
  `xm16` int DEFAULT NULL,
  `xm16_jj` int DEFAULT NULL,
  `xm16_mm` int DEFAULT NULL,
  `xm16_aaaa` int DEFAULT NULL,
  `xm17` int DEFAULT NULL,
  `xm17h` int DEFAULT NULL,
  `xm17l` int DEFAULT NULL,
  `xm50` int DEFAULT NULL,
  `xm20` int DEFAULT NULL,
  `xm30` int DEFAULT NULL,
  `xm40` int DEFAULT NULL,
  `xm60` int DEFAULT NULL,
  `xm41` int DEFAULT NULL,
  `d00` int DEFAULT NULL,
  `d01` int DEFAULT NULL,
  `ag01` int DEFAULT NULL,
  `ag01b` int DEFAULT NULL,
  `em00` int DEFAULT NULL,
  `em01` int DEFAULT NULL,
  `intro_membre` int DEFAULT NULL,
  `nb_residents` int DEFAULT NULL,
  `nb_resident_presents` int DEFAULT NULL,
  `nb_rp_h` int DEFAULT NULL,
  KEY `idx_menage_geo_filters` (`code_region`,`code_departement`,`code_commune`,`mo_zd`),
  KEY `idx_menage_stats` (`level-1-id`,`xm40`,`nb_residents`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;