module.exports = {
  region: {
    label: 'Régions',
    table: 'region',
    columns: ['id', 'code', 'libelle'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: [],
    roles: ['ROLE_GLOBAL']
  },

  departement: {
    label: 'Départements',
    table: 'departement',
    columns: ['id', 'code', 'libelle', 'region_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL']
  },

  commune: {
    label: 'Communes',
    table: 'commune',
    columns: ['id', 'code', 'libelle', 'departement_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL']
  },

  zd: {
    label: 'Zones de dénombrement',
    table: 'zd',
    columns: ['id', 'code', 'libelle', 'commune_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  menage: {
    label: 'Ménages',
    table: 'menage',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'zd_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune', 'zd'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  agriculture: {
    label: 'Agriculture',
    table: 'agriculture',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'zd_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune', 'zd'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  elevage: {
    label: 'Élevage',
    table: 'elevage',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'zd_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune', 'zd'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  deces: {
    label: 'Décès',
    table: 'deces',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'zd_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune', 'zd'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  emigration: {
    label: 'Émigration',
    table: 'emigration',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'zd_id'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune', 'zd'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  },

  stats_par_departement: {
    label: 'Statistiques par département',
    table: 'stats_par_departement',
    columns: ['id', 'region_id', 'departement_id', 'indicateur', 'valeur'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL']
  },

  stats_par_commune: {
    label: 'Statistiques par commune',
    table: 'stats_par_commune',
    columns: ['id', 'region_id', 'departement_id', 'commune_id', 'indicateur', 'valeur'],
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region', 'departement', 'commune'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL', 'ROLE_DEPARTEMENTAL', 'ROLE_COMMUNAL']
  }
};

module.exports = {
  stats_nationales: {
    label: 'Statistiques nationales',
    table: 'stats_nationales',
    columns: [
      'id',
      'total_menages_attendu',
      'total_menages',
      'total_population',
      'nb_menages_plus_10',
      'nb_menages_solo',
      'population_rurale',
      'menages_enumeres',
      'menages_denombres',
      'population_carto',
      'population_collectee',
      'average_deces',
      'hommes',
      'femmes',
      'nb_enfants_moins_5',
      'nb_residents_absents',
      'nb_visiteurs',
      'nb_naissances_vivantes',
      'nb_femmes_15_49',
      'menages_agricoles',
      'total_emigres',
      'menages_avec_emigres',
      'date_maj'
    ],
    filterColumns: {},
    allowedFormats: ['csv', 'json', 'excel'],
    filters: [],
    roles: ['ROLE_GLOBAL']
  },

  stats_par_region: {
    label: 'Statistiques par région',
    table: 'stats_par_region',
    columns: [
      'id',
      'code_region',
      'region',
      'total_menages_attendu',
      'total_menages',
      'total_population',
      'nb_menages_plus_10',
      'nb_menages_solo',
      'population_rurale',
      'menages_enumeres',
      'menages_denombres',
      'population_carto',
      'population_collectee',
      'average_deces',
      'hommes',
      'femmes',
      'nb_enfants_moins_5',
      'nb_residents_absents',
      'nb_visiteurs',
      'nb_naissances_vivantes',
      'nb_femmes_15_49',
      'menages_agricoles',
      'total_emigres',
      'menages_avec_emigres',
      'date_maj'
    ],
    filterColumns: {
      region: 'code_region'
    },
    allowedFormats: ['csv', 'json', 'excel'],
    filters: ['region'],
    roles: ['ROLE_GLOBAL', 'ROLE_REGIONAL']
  },
  menage: {
    label: 'Ménages',
    table: 'menage',
    columns: [
      'menage-id',
      'level-1-id',
      'id01',
      'id02',
      'id03',
      'id05',
      'id06',
      'id07',
      'id10',
      'xm01',
      'xm04',
      'xm06',
      'xm08',
      'xm08lo',
      'xm08la',
      'xm09',
      'xm10',
      'xm11',
      'xm11_jj',
      'xm11_mm',
      'xm11_aaaa',
      'xm12',
      'xm12h',
      'xm12m',
      'xm13',
      'xm13_jj',
      'xm13_mm',
      'xm13_aaaa',
      'xm14',
      'xm14h',
      'xm14m',
      'xm50',
      'xm20',
      'xm30',
      'xm40',
      'xm60',
      'xm41',
      'd00',
      'd01',
      'ag01',
      'ag01b',
      'em00',
      'em01',
      'intro_membre',
      'meta_rep',
      'meta_start',
      'meta_end',
      'meta_last_modify_date',
      'meta_duration',
      'meta_calc_duration',
      'meta_intro',
      'tel_repondant',
      'men_exist_denombrement',
      'ag02h(1)',
      'ag02h(2)',
      'ag02h(3)',
      'ag02h(4)',
      'ag02h(5)',
      'ag02h(6)',
      'ag02h(7)',
      'ag02h(8)',
      'ag02h(9)',
      'ag02h(10)',
      'ag02h(11)',
      'ag02h(12)',
      'ag02h(13)',
      'ag02h(14)'
    ],
    defaultPreviewColumns: [
      'menage-id',
      'level-1-id',
      'id01',
      'id02',
      'id03',
      'xm01',
      'xm04',
      'xm06',
      'ag01',
      'em01'
    ],
    filterColumns: {},
    allowedFormats: ['csv', 'json', 'excel'],
    filters: [],
    roles: ['ROLE_GLOBAL'],
    previewLimit: 20,
    exportLimit: 1000000
  },

  caracteristique: {
  label: 'Caractéristiques',
  table: 'caracteristique',
  columns: [
    'caracteristique-id',
    'level-1-id',
    'occ',
    'c00',
    'c01n',
    'c01p',
    'c01',
    'c02',
    'c03',
    'c04',
    'c05',
    'c05_jj',
    'c05_mm',
    'c05_aaaa',
    'c06',
    'c07p',
    'c07r',
    'c07d',
    'c07c',
    'c08a',
    'c08b',
    'c09',
    'c10',
    'c10_a',
    'c11',
    'c11a',
    'c12',
    'c12pra',
    'c12rra',
    'c12dra',
    'c12cra',
    'c12mra',
    'c12mra_a',
    'c12lpra',
    'c13p',
    'c13r',
    'c13d',
    'c13c',
    'c13m',
    'c13m_a',
    'c13lp',
    'c14p',
    'c14r',
    'c14d',
    'c14c',
    'c14m',
    'c14m_a',
    'c14lp',
    'c14me',
    'c14ae',
    'c16',
    'c17',
    'c18a',
    'c18b',
    'c18c',
    'c18d',
    'c18e',
    'c18f',
    'c18g',
    'c18h',
    'c19a',
    'c19b',
    'c19c',
    'c19d',
    'c19e',
    'c19ec',
    'c19f',
    'c20',
    'c20a',
    'c21',
    'c21a',
    'c21b',
    'c22',
    'c23',
    'c24',
    'c24a',
    'c25',
    'c25a',
    'c26',
    'c26a',
    'c26b',
    'c27t',
    'c27m',
    'c27f',
    'c28t',
    'c28m',
    'c28f',
    'c29',
    'c29a',
    'c29a_jj',
    'c29a_mm',
    'c29a_aaaa',
    'c29b',
    'c29c',
    'c30t',
    'c30m',
    'c30f',
    'c31t',
    'c31m',
    'c31f',
    'c32',
    'c33',
    'ind_status',
    'membre_controle',
    'is_deleted',
    'temp_nais',
    'temp_migration',
    'temp_migration_1',
    'temp_survi',
    'temp_handicap',
    'temp_activite',
    'temp_education',
    'temp_etat_matrimonial',
    'temp_fecondite',
    'temp_tic'
  ],
  defaultPreviewColumns: [
    'caracteristique-id',
    'level-1-id',
    'occ',
    'c00',
    'c01n',
    'c01p',
    'c01',
    'c02',
    'c03',
    'c04',
    'c05',
    'c06'
  ],
  filterColumns: {},
  allowedFormats: ['csv', 'json', 'excel'],
  filters: [],
  roles: ['ROLE_GLOBAL'],
  previewLimit: 20,
  exportLimit: 1000000
}
};